[project]
name = "adventofcode2025"
version = "0.1.0"
description = ""
authors = [{name = "Uy Nguyen"}]
readme = "README.md"
requires-python = ">=3.14"
dependencies = []

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
